Add files via upload
vinchevskaya/TAT_2018 pull request #3
Opened 2018-03-06 21:42 UTC by vinchevskaya

2018-03-07 17:45 UTC, IgorKheidorov requested changes

2018-03-07 17:45 UTC, IgorKheidorov commented on DEV-3/ConverterOfNumber.cs
> +            string resultNamber = "";
Grammar error, Number

2018-03-07 17:45 UTC, IgorKheidorov commented on DEV-3/ConverterOfNumber.cs
> +                {
Maybe much more effective use 'A'-10 as a constant not calculate each time?

2018-03-07 17:45 UTC, IgorKheidorov commented on DEV-3/ConverterOfNumber.cs
> +                {
It seem that it will not work, bug. Please test, '0' is not 0

2018-03-07 17:45 UTC, IgorKheidorov commented on DEV-3/ConverterOfNumber.cs
> +        /// <returns>Converted string.</returns>
Convert not converse

2018-03-07 17:45 UTC, IgorKheidorov commented on DEV-3/EntryPoint.cs
> +                }
Why do you not simply pass decimalNumber and newRadix to method

2018-03-07 17:45 UTC, IgorKheidorov commented on DEV-3/EntryPoint.cs
> +            {
why do not not check for number of arguments?

2018-03-07 17:45 UTC, IgorKheidorov commented on DEV-3/ConverterOfNumber.cs
> +            int decimalNumber = ConvertNumber;
What about decimalNumber  = 0?

2018-03-08 19:23 UTC, AlexanderSoroka approved these changes

2018-03-08 19:23 UTC, AlexanderSoroka commented on DEV-3/ConverterOfNumber.cs
> +            if (decimalValues < 0)
it's better to implement custom setter/getter instead all these checks

2018-03-15 18:37 UTC, merged